### PR TITLE
updating packages

### PR DESCRIPTION
**Pull request by HalcyonJAC**
I have resolved some security vulnerabilities by doing the following:
- upgrading some packages
- installing some peer dev dependancies manually
- force secure versions of some nested dependancies to be used, by adding a `resolutions` section to the `package.json` file.

The end result is that now after running `npm install` it only warns about 1 low priority vulnerability, i.e. no moderate, high or ciritical ones at all. :)

### CODE REVIEW

**Comment by lloback** [comment]
Initially it asked to install the `npm-force-resolutions`
```
loback@MacBook-Pro jac-kit (security/22-npm-audit) $ npm install

> jac-kit@0.1.0 preinstall
> npx npm-force-resolutions

Need to install the following packages:
  npm-force-resolutions
Ok to proceed? (y) y

added 1392 packages, removed 192 packages, and audited 3873 packages in 5m

3 low severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
```

But then, the next time I tried to run `npm install` got an error:

image


Do we need to remove the

```
"resolutions": {
    "postcss": "^8.2.15",
    "trim": "^1.0.1"
  }
```

After the pckage.lock.js file is updated?

**Comment by HalcyonJAC** [comment]
Hi @lloback, thanks for reviewing this. Yes, the `postcss` package should not have been included in the `resolutions` section, only the `trim` package needed to be there. I have pushed another couple of commits up now, partly to fix this problem but also to upgrade some other packages - figured I may as well go all-in.

**Review by mbrookeswebdev — APPROVED** [review]

**Comment by mbrookeswebdev** [comment]
I couldn't run npm install -

Screenshot 2021-05-21 at 10 21 34
Screenshot 2021-05-21 at 10 19 47

**Comment by HalcyonJAC** [comment]
@mbrookeswebdev please make sure you have `npx` installed first by running `npm install -g npx`

**Comment by lloback** [comment]
`npm run build` returns an error:

```

 ERROR  Failed to compile with 1 error                                                                                         20:58:29

This relative module was not found:

* ./components/HelloWorld.vue in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=script&lang=js&
 ERROR  Build failed with errors.
```

`npm run serve` return the following error:
```
npm run serve

> jac-kit@0.1.0 serve
> vue-cli-service serve

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
 INFO  Starting development server...
10% building 2/2 modules 0 active(node:10246) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
98% after emitting CopyPlugin

 ERROR  Failed to compile with 1 error                                                                                         21:00:54

This relative module was not found:

 ./components/HelloWorld.vue in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=script&lang=js&
```

10 tests failed.

The good news is that the storybook fires up

**Comment by HalcyonJAC** [comment]
@lloback I just checked out a previous version of the main `develop` branch date 19/03/2021, that has label @jac-uk/jac-kit@0.0.34 and the same 10 tests fail (see below).

`npm run serve` also returns an error for that version of the source code too.

so, now I don't know what to do...

image

**Comment by HalcyonJAC** [comment]
@warrensearle I need your advice on the above findings please...progress has stalled on this ticket and I am not sure how best to move it forwards

**Comment by warrensearle** [comment]
Hey @HalcyonJAC and @lloback 

I have created a separate task for fixing the broken tests here:
https://github.com/jac-uk/jac-kit/issues/32
They were broken before this PR so outside the scope of this piece of work

We should expect storybook to run individual components but we can ignore the `npm run serve` and `npm run build` issues. 
As noted in the README file we are not currently using the repo for Vue development and I don't recall us ever having run the project as a full vue app. I suspect the two scripts are inherited from the project (Admin repo) the JAC Kit was seeded from.

**Comment by HalcyonJAC** [comment]
Thanks @warrensearle 

@lloback are you ok approving this now, following Warren's comment above?

**Comment by lloback** [comment]
I can approve the PR - it is fine, because the packages that were updated, they work.
My issue, is that after this PR goes in we still have hight risk vulnerabilities.

```
v10.16.0 found 251 vulnerabilities (1 low, 231 moderate, 19 high)

v14.2.0 108 vulnerabilities (3 low, 93 moderate, 12 high)

v16.1.0  108 vulnerabilities (3 low, 93 moderate, 12 high)
```

**Comment by HalcyonJAC** [comment]
Hi - when running `npm audit --production` (which checks only non-dev packages) there are no vulnerabilities:

```
v16.3.0  found 0 vulnerabilities

v14.17.0  found 0 vulnerabilities

v12.22.1  found 0 vulnerabilities
```

Note: this command is not available in npm <6.10

**Review by lloback — APPROVED** [review]
As per @warrensearle comments on the other PR, approving.

**Review by mbrookeswebdev — APPROVED** [review]

**Pull request merged**
